name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '13', '15' ]
    name: Java ${{ matrix.Java }} 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Run Tests
        run: mvn test

